/**
 * Static provider alias data extracted from providerRegistry.
 *
 * REGISTRY_ID_TO_ALIAS maps canonical provider ID -> display alias for
 * every entry whose alias differs from its ID.  MANUAL_ALIAS_OVERRIDES
 * lists slug-style prefixes that resolve to canonical IDs but live
 * outside the registry (multi-provider slugs, backward-compat renames).
 *
 * Both maps are consumed by src/shared/utils/providerAlias.ts so that
 * browser and server resolve identically.  A drift gate in
 * tests/unit/provider-alias-drift.test.ts fails when the registry
 * changes and this file is not updated.
 */

/** Provider ID -> display alias (non-identity entries only). */
export const REGISTRY_ID_TO_ALIAS: Record<string, string> = {
  "adapta-web": "adp-web",
  aimlapi: "aiml",
  alibaba: "ali",
  "alibaba-cn": "ali-cn",
  "ant-ling": "ling",
  "api-airforce": "af",
  "arcee-ai": "arcee",
  auggie: "aug",
  "bailian-coding-plan": "bcp",
  bazaarlink: "bzl",
  blackbox: "bb",
  "blackbox-web": "bb-web",
  bluesminds: "bm",
  byteplus: "bpm",
  "chatgpt-web-codex": "cgpt-codex",
  cheaperinference: "cinf",
  chipotle: "pepper",
  claude: "cc",
  "claude-web": "cw",
  cline: "cl",
  clinepass: "cp",
  "cloudflare-ai": "cf",
  "cloudflare-playground": "cfp",
  "clova-studio": "clova",
  "codebuddy-cn": "cbcn",
  codex: "cx",
  "codex-app-server": "cxa",
  "command-code": "cmd",
  "conol-web": "cnl",
  "copilot-m365-web": "m365copilot",
  cursor: "cu",
  "cursor-api": "cua",
  deepseek: "ds",
  "deepseek-web": "ds-web",
  "devin-cli": "dv",
  "devin-cli-agentic": "dva",
  dit: "dai",
  "doubao-web": "db",
  "duckduckgo-web": "ddgw",
  "featherless-ai": "featherless",
  freeaiapikey: "faik",
  freebuff: "fb",
  "freemodel-dev": "fmd",
  freetheai: "fta",
  friendliai: "friendli",
  "g4f-gemini": "g4fgem",
  "g4f-groq": "g4fgroq",
  "g4f-nvidia": "g4fnv",
  "g4f-ollama": "g4foll",
  "g4f-pollinations": "g4fpol",
  "gemini-business": "gembiz",
  "gemini-web": "gweb",
  github: "gh",
  "gitlab-duo": "gld",
  gitlawb: "glb",
  "gitlawb-gmi": "glb-gmi",
  "glm-cn": "glmcn",
  "grok-cli": "gc",
  "grok-web": "gw",
  haiper: "hp",
  huggingface: "hf",
  hyperagent: "ha",
  hyperbolic: "hyp",
  ideogram: "ideo",
  "inference-net": "inet",
  "inner-ai": "in-ai",
  "kilo-gateway": "kg",
  kilocode: "kc",
  "kimi-coding": "kmc",
  "kimi-coding-apikey": "kmca",
  kiro: "kr",
  "lambda-ai": "lambda",
  leonardo: "leo",
  "llm-kiwi": "llmkiwi",
  lmarena: "lma",
  longcat: "lc",
  maxai: "mx",
  "meta-llama": "meta",
  modelscope: "ms",
  monsterapi: "monster",
  "muse-code": "mc",
  "muse-spark-web": "ms-web",
  "naga-ac": "naga",
  nlpcloud: "nlpc",
  "notion-web": "nw",
  "nous-research": "nous",
  "ollama-cloud": "ollamacloud",
  oneminai: "1min",
  openadapter: "oad",
  opencode: "oc",
  openference: "of",
  "openference-api": "ofa",
  ovhcloud: "ovh",
  perplexity: "pplx",
  "perplexity-agent": "pplx-agent",
  "perplexity-web": "pplx-web",
  pioneer: "pn",
  pollinations: "pol",
  promptql: "pql",
  qoder: "if",
  "qwen-cloud": "qwc",
  "qwen-cloud-token-plan": "qct",
  sambanova: "samba",
  scaleway: "scw",
  seekai: "ska",
  "t3-web": "t3chat",
  "tencent-aistudio-web": "tasw",
  "tinycms-web": "tcw",
  "token-kiosk": "tk",
  tokenrouter: "trk",
  trae: "tr",
  uc: "ucn",
  "uc-direct": "ucd",
  uncloseai: "unc",
  "v0-vercel": "v0",
  "veoaifree-web": "veo-free",
  "vercel-ai-gateway": "vag",
  "vertex-partner": "vp",
  "volcengine-agent-plan": "veap",
  "volcengine-coding-plan": "vecp",
  "xai-oauth": "xao",
  "xiaomi-mimo": "mimo",
  "xiaomi-mimo-token-plan": "mimotp",
  "yuanbao-web": "ybw",
  "zai-web": "zw",
  zcode: "zc",
  zenmux: "zm",
  "zenmux-free": "zmf",
  "zylo-api": "zylo",
};

/**
 * Manual alias overrides that live outside registry entries.
 * Maps user-facing slug prefix -> canonical provider ID.
 */
export const MANUAL_ALIAS_OVERRIDES: Record<string, string> = {
  opencode: "opencode-zen",
  xiaomi: "xiaomi-mimo",
  llamacpp: "llama-cpp",
  agy: "antigravity",
  aq: "amazon-q",
};
